Feat: Add configurable shipping price free above price
redjepakketje/magento-shipping pull request #6
Opened 2021-09-08 08:35 UTC by QuentenZ

Field added to configure a price for RedjePakketje from which the shipping price will be free.

2021-09-08 08:45 UTC, JeroenVanLeusden requested changes

2021-09-08 08:45 UTC, JeroenVanLeusden commented on src/etc/adminhtml/system.xml
> +                    <label>Free shipping price</label>
```suggestion
                    <label>Free shipping price</label>
                    <validate>validate-number validate-zero-or-greater</validate>
```

2021-09-08 08:45 UTC, JeroenVanLeusden commented on src/etc/adminhtml/system.xml
> +                    <label>Free shipping price</label>
We should add validation to make sure input is always a number.

2022-10-11 14:46 UTC, arjanvdbos commented
This module is marked as deprecated and no longer supported.

2022-10-11 14:46 UTC, closed without merging